export enum Languages {
  JAVASCRIPT = "javascript",
  PYTHON = "python",
  GOLANG = "golang",
  JAVA = "java",
  C = "c",
  CPP = "cpp",
  CSHARP = "csharp",
  RUBY = "ruby",
  SWIFT = "swift",
  PHP = "php",
  TYPESCRIPT = "typescript",
  KOTLIN = "kotlin",
  RUST = "rust",
  SCALA = "scala",
  R = "r",
  PERL = "perl",
  HASKELL = "haskell",
  LUA = "lua",
  ELIXIR = "elixir",
  CLOJURE = "clojure",
  DART = "dart",
  JULIA = "julia",
}
