export enum Languages {
  JAVASCRIPT = 'javascript',
  PYTHON = 'python',
  GO = 'go',
  JAVA = 'java',
  // RUST = 'rust',
  C = "c",
  CPP = "cpp",
  // CSHARP = "csharp",
  // RUBY = "ruby",
  // SWIFT = "swift",
  // PHP = "php",
  // TYPESCRIPT = "typescript",
  // KOTLIN = "kotlin",
  // SCALA = "scala",
  // R = "r",
  // PERL = "perl",
  // HASKELL = "haskell",
  // LUA = "lua",
  // ELIXIR = "elixir",
  // CLOJURE = "clojure",
  // DART = "dart",
  // JULIA = "julia",
}
